### ISSUE TITLE
Cannot load JAR packaged `application.properties` file with Spring framework when switching to Java 11

### ISSUE THREAD

**Issue by cbismuth** [Azure/azure-functions-java-worker#589] opened 2022-06-20 14:54 UTC
Dear Azure Functions Java team,

We're trying to upgrade our Java based Azure functions to Java 11, but the Spring framework cannot load JAR packaged `application.properties` file when switching our functions to Java 11.

Java and Maven versions:

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Java version: 11.0.15, vendor: Azul Systems, Inc., runtime: /Users/cbismuth/Library/Java/JavaVirtualMachines/azul-11.0.15/Contents/Home
```

We've already upgraded to the latest Azure runtime v4, and here are the latest Maven dependency versions we use:

```
<azure-functions-maven-plugin.version>1.18.0</azure-functions-maven-plugin.version>
<azure-functions-java-library.version>2.0.1</azure-functions-java-library.version>
```

We can reproduce the issue on our laptops using `mvn -U azure-functions:run` Maven command line.

Using Java 8 everything works fine, but when switching to Java 11 the Spring application context failed to load in the function with the error below.

(A simple `main`-like application just loading the Spring application context works fine with Java 11.)

Error:

`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [fr.tf1.data.commons.config.SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist`

Stack trace:

```
Azure Functions Core Tools
Core Tools Version:       4.0.4590 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.5.2.18383


Functions:

        git: [GET] http://localhost:7071/api/git

        graphRecommendProgramIds: [GET] http://localhost:7071/api/v1/programs/{userId}

        graphRecommendVideoIds: [GET] http://localhost:7071/api/v1/videos/{userId}

        health: [GET] http://localhost:7071/api/health

        jvm: [GET] http://localhost:7071/api/jvm

For detailed output, run func with --verbose flag.
[2022-06-20T14:39:26.004Z] Worker process started and initialized.
[2022-06-20T14:39:26.078Z] [WARNING] {JavaFunctionBroker.addJavaAnnotationLibrary}: Customer is not providing java annotation files, they may not use the latest version of java library and maven plugin.
[2022-06-20T14:39:26.079Z] [WARNING] {JavaFunctionBroker.addJavaAnnotationLibrary}: Customer is not providing java annotation files, they may not use the latest version of java library and maven plugin.
[2022-06-20T14:39:26.079Z] [WARNING] {JavaFunctionBroker.addJavaAnnotationLibrary}: Customer is not providing java annotation files, they may not use the latest version of java library and maven plugin.
[2022-06-20T14:39:26.079Z] [WARNING] {JavaFunctionBroker.addJavaAnnotationLibrary}: Customer is not providing java annotation files, they may not use the latest version of java library and maven plugin.
[2022-06-20T14:39:26.079Z] [WARNING] {JavaFunctionBroker.addJavaAnnotationLibrary}: Customer is not providing java annotation files, they may not use the latest version of java library and maven plugin.
[2022-06-20T14:39:26.562Z] juin 20, 2022 4:39:26 PM org.springframework.context.annotation.AnnotationConfigApplicationContext refresh
[2022-06-20T14:39:26.562Z] AVERTISSEMENT: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [fr.tf1.data.commons.config.SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist
[2022-06-20T14:39:26.572Z] 16:39:26.570 [pool-2-thread-3] ERROR f.t.d.c.config.SpringBeanProvider - Failed to parse configuration class [fr.tf1.data.commons.config.SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [fr.tf1.data.commons.config.SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
    at fr.tf1.data.commons.config.SpringBeanProvider.<init>(SpringBeanProvider.java:96)
    at fr.tf1.data.commons.config.SpringBeanProvider.initialize(SpringBeanProvider.java:47)
    at fr.tf1.data.commons.config.SpringBeanProvider.getInstance(SpringBeanProvider.java:30)
    at fr.tf1.data.commons.config.SpringBeanProvider.getBean(SpringBeanProvider.java:57)
    at fr.tf1.data.recommendation.graph.function.AbstractRecommendationFunction.<clinit>(AbstractRecommendationFunction.java:31)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:398)
    at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.getContainingClass(EnhancedJavaMethodExecutorImpl.java:63)
    at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.<init>(EnhancedJavaMethodExecutorImpl.java:22)
    at com.microsoft.azure.functions.worker.broker.FactoryJavaMethodExecutor.getJavaMethodExecutor(FactoryJavaMethodExecutor.java:20)
    at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:38)
    at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
    at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
    at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
    at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist
    at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199)
    at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:159)
    at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:110)
    at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:81)
    at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:67)
    at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:67)
    at org.springframework.core.io.support.DefaultPropertySourceFactory.createPropertySource(DefaultPropertySourceFactory.java:37)
    at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:463)
    at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:280)
    at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207)
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175)
... 26 common frames omitted

[2022-06-20T14:39:26.606Z] 16:39:26.572 [pool-2-thread-3] ERROR f.t.d.c.config.SpringBeanProvider - org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [fr.tf1.data.commons.config.SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist java.lang.RuntimeException: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [fr.tf1.data.commons.config.SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist
    at fr.tf1.data.commons.config.SpringBeanProvider.<init>(SpringBeanProvider.java:104)
    at fr.tf1.data.commons.config.SpringBeanProvider.initialize(SpringBeanProvider.java:47)
    at fr.tf1.data.commons.config.SpringBeanProvider.getInstance(SpringBeanProvider.java:30)
    at fr.tf1.data.commons.config.SpringBeanProvider.getBean(SpringBeanProvider.java:57)
    at fr.tf1.data.recommendation.graph.function.AbstractRecommendationFunction.<clinit>(AbstractRecommendationFunction.java:31)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:398)
    at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.getContainingClass(EnhancedJavaMethodExecutorImpl.java:63)
    at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.<init>(EnhancedJavaMethodExecutorImpl.java:22)
    at com.microsoft.azure.functions.worker.broker.FactoryJavaMethodExecutor.getJavaMethodExecutor(FactoryJavaMethodExecutor.java:20)
    at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:38)
    at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
    at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
    at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
    at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [fr.tf1.data.commons.config.SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
    at fr.tf1.data.commons.config.SpringBeanProvider.<init>(SpringBeanProvider.java:96)
... 19 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist
    at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199)
    at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:159)
    at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:110)
    at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:81)
    at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:67)
    at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:67)
    at org.springframework.core.io.support.DefaultPropertySourceFactory.createPropertySource(DefaultPropertySourceFactory.java:37)
    at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:463)
    at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:280)
    at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207)
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175)
... 26 common frames omitted

[2022-06-20T14:39:30.098Z] Host lock lease acquired by instance ID '000000000000000000000000743AEE76'.
```

Spring application context:

```java
@Configuration
@EnableScheduling
@EnableTransactionManagement
@ComponentScan("fr.tf1.data")
@PropertySource("classpath:application.properties")
public class SpringConfig {

    private static final Logger LOGGER = LoggerFactory.getLogger(SpringConfig.class);

    @Bean
    public static PropertySourcesPlaceholderConfigurer propertyPlaceholderConfigurer() {
        return new PropertySourcesPlaceholderConfigurer();
    }

    @Bean
    public ConversionService conversionService() {
        return new DefaultConversionService();
    }

    @Bean
    public PersistenceExceptionTranslationPostProcessor persistenceExceptionTranslationPostProcessor() {
        return new PersistenceExceptionTranslationPostProcessor();
    }
}
```

Spring application loading code:

```java
    private SpringBeanProvider(final String... args) {
        final Stopwatch stopwatch = Stopwatch.createStarted();

        try {
            applicationContext = new AnnotationConfigApplicationContext();

            if (args.length != 0) {
                applicationContext.getEnvironment()
                                  .getPropertySources()
                                  .addFirst(new SimpleCommandLinePropertySource(args));
            }

            applicationContext.register(SpringConfig.class);

            applicationContext.refresh();

            Runtime.getRuntime().addShutdownHook(new Thread(applicationContext::close));

            LOGGER.info("Spring application context successfully started in [{}]", DateHelper.toPrintablePeriod(stopwatch));
        } catch (final Throwable e) {
            LOGGER.error(e.getMessage(), e);

            throw new RuntimeException(e);
        }
    }
```

**Comment by kaibocai** [comment] 2022-06-20 19:32
Hi @cbismuth , thanks for reaching out with the issue, can you share a repo for sample project (it will save us time on configuration and focus on resolving the issue) that we can use to reproduce the issue. Thanks a lot.

**Comment by cbismuth** [comment] 2022-06-21 12:51
Hi @kaibocai, issue found, it occurred when a Spring component is loaded statically from a function class definition, as shown below:

https://github.com/cbismuth/azure-functions-java-worker-issue-589/blob/1733b006cb196f64374547fa43a1520583c36e06/function/src/main/java/com/github/cbismuth/azfuncjava11/SampleFunction.java#L16

No issue when the `environment` bean is loaded inside the function code or when the `static` modifier is removed in the field declaration.

I don't know why this worked well in Azure functions with Java 11.

**Comment by kaibocai** [comment] 2022-06-21 14:11
> I don't know why this worked well in Azure functions with Java 11.

You mean worked well with Java 8 right. Also, did you only observe this issue when in function definition class, for normal class we don't have this issue? Thank you.

**Comment by cbismuth** [comment] 2022-06-21 14:16
Ouch, yes sorry: I don't know why this worked well in Azure functions with Java **8**.

**Comment by kaibocai** [comment] 2022-06-22 18:30
Hi @cbismuth, we are continuing investigating the issue, at mean time I found you are using spring with azure functions, just want to check have you ever consider using spring cloud function based on azure functions where you can find samples [here](https://github.com/Azure-Samples/hello-spring-function-azure), it will enables you to use spring boot just as a normal spring boot application and you can bind properties using `@Value` annotation that works in normal spring boot app. Thanks.

**Comment by cbismuth** [comment] 2022-06-22 18:44
Hi @kaibocai, thanks a lot for your support.

We started to use Spring framework long before Spring Cloud Functions were available, and we don't plan to migrate as everything will hopefully work well when removing the `static` modifier with Java 11.

We don't want to use Spring Boot as it brings too many dependencies and we want to keep our project lightweight and tidy. Spring Context is enough for us with Azure function annotations (`HttpTrigger` and `EventHubTrigger`). We talked about with @jdubois back in 2019 or so.

**Comment by cbismuth** [comment] 2022-06-22 19:41
@kaibocai I came across this documentation section with Java 1.8 as a prerequisite for the Maven plugin, is it outdated? thanks

https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions#prerequisites

**Comment by kaibocai** [comment] 2022-06-22 20:45
Hi @cbismuth , yes it's out of date, it supports 1.8 and 11. Will update the page soon. Thank you.

**Comment by kaibocai** [comment] 2022-06-23 21:27
Hi @cbismuth , thanks again for open this issue. We have found the root cause, it's due to a bug in azure function java worker. Put it simple, the classloader(system classloader) that used to load static fields are different as the classloader(classloader defined by ourself) that used to load non-static fields. That's why when use static key world, the wrong classloader cannot find the resources as it don't have the resource. We will fix the bug and have a new release as soon as possible. 

Current **workaround** is remove the static key world. Thanks very much. 

For **java8**, it works because we are using system classloader to load all resources which is not the case in java11.

**Comment by cbismuth** [comment] 2022-06-24 12:59
Thanks @kaibocai 👍 classloaders have always been tricky bits ;)

**Closed as completed** 2022-08-01 16:30 UTC
Labels: Bug
