### ISSUE TITLE
Functions with the same package path and method name will not co-exist under the same Function App.

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-functions-java-worker#68] opened 2018-03-09 20:42 UTC
## Symptoms
If two Functions are deployed into the same application the loader tries to find both Functions in the first Jar and the the language worker exits.

## Logs

info: Host.General[0]
      Starting Host (HostId=fincom-functions-201803071535451, Version=2.0.11587.0, ProcessId=5488, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=beta)
Found the following functions:
Host.Functions.goodbye
Host.Functions.hello
info: Host.Startup[0]
      Found the following functions:
      Host.Functions.goodbye
      Host.Functions.hello
      
Job host started
info: Host.Startup[0]
      Job host started
info: Host.General[0]
      Host lock lease acquired by instance ID '7883d528e2f2fd79a0b584d02a135ee1'.
info: Worker.Java.076a6a45-e40a-4b03-a657-a9078a7baf4c[0]
      Microsoft Azure Functions Java Runtime [build 1.0.0-beta-3]
info: Host.Executor[0]
      => RequestId:0HLC53OESPDU9:00000002 RequestPath:/api/goodbye => System.Collections.Generic.Dictionary`2[System.String,System.Object] => System.Collections.Generic.Dictionary`2[System.String,System.Object]
      Function started (Id=d0f52bf2-9be7-420f-b319-4982b5d3f8a6)
Executing 'Functions.goodbye' (Reason='This function was programmatically called via the host APIs.', Id=d0f52bf2-9be7-420f-b319-4982b5d3f8a6)
info: Worker.Java.076a6a45-e40a-4b03-a657-a9078a7baf4c[0]
      [INFO] {MessageHandler.handle}: Message generated by "StartStream.Builder"
info: Worker.Java.076a6a45-e40a-4b03-a657-a9078a7baf4c[0]
      Worker initialized
info: Worker.Java.076a6a45-e40a-4b03-a657-a9078a7baf4c[0]
      "goodbye" loaded (ID: ad30c8fd-e9ed-468c-a8c5-120cf943901b, Reflection: "D:\home\site\wwwroot\fincom-airport-1.0-SNAPSHOT.jar"::"com.fincom.functions.Function.goodbye")
warn: Worker.Java.076a6a45-e40a-4b03-a657-a9078a7baf4c[0]
      There are no methods named "hello" in class "com.fincom.functions.Function"
info: Worker.Java.076a6a45-e40a-4b03-a657-a9078a7baf4c[0]
      [SEVERE] {Application.main}: Unexpected Exception causes system to exit
info: Worker.Java.076a6a45-e40a-4b03-a657-a9078a7baf4c[0]

Here are my POM.xml snippets.

Hello Function

    <groupId>com.fincom.functions</groupId>
    <artifactId>fincom-functions</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Azure Java Functions</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <functionAppName>fincom-functions-20180307153545156</functionAppName>
        <functionAppRegion>west europe</functionAppRegion>
    </properties>

Goodbye Function

    <groupId>com.fincom.functions</groupId>
    <artifactId>fincom-airport</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Azure Java Functions</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <functionAppName>fincom-functions-20180307153545156</functionAppName>
        <functionAppRegion>west europe</functionAppRegion>
    </properties>

## Function,Json Snippets
For Hello

  "scriptFile" : "..\\fincom-functions-1.0-SNAPSHOT.jar",
  "entryPoint" : "com.fincom.functions.Function.hello",

For Goodbye

  "scriptFile": "..\\fincom-airport-1.0-SNAPSHOT.jar",
  "entryPoint": "com.fincom.functions.Function.goodbye",

## Steps to repro
1) Create a Java Function as normal.
2) Build and Deploy.
3) Create a second Function as step 1 and re-use the same App Name and GroupId.
4) Deploy the second Function to the same App.
5) Invoking either will cause the symptoms as above to happen.

## Workaround
The only workaround is to not share the GroupId

**Comment by kevinhillinger** [comment] 2018-04-24 16:40
I attempted to duplicate this issue. After review the posted log output and verifying it myself, this issue does not have anything to do with the same group id. What is happening is the same package path PLUS the same class name is being used between the two jars. Java's class loader will select the first one that's loaded.  I confirmed this by changing jar 1 function to ```Function1```, and jar 2 function to ```Function2```.

This isn't a bug and Functions worker is functioning properly. This type of problem is precisely why Java uses the package naming convention that it does to avoid conflicts. The worker will support multiple jars being deployed.

Recommendation is to not have matching package paths and class name in two different jars. This is standard practice.

**Comment by FinVamp1** [comment] 2018-04-25 19:43
Thanks Kevin, this did work before the PR in https://github.com/Azure/azure-functions-java-worker/pull/50 and I understand your logic. @JunyiYi it would be good to have this covered in the documentation.

**Comment by pragnagopa** [comment] 2018-05-10 17:56
@junyi - This is a very difficult issue to diagnose as there are no error details. Worker needs to provide appropriate error message so that host can properly propagate erorrs to user logs.

**Comment by JunyiYi** [comment] 2018-05-17 00:03
We don't think it makes sense to create two jar files in one function app. We support (and recommend) multiple functions in one single jar file, for example:
```
fincom-functions-1.0-SNAPSHOT.jar
  --> com.fincom.functions.Function.hello
  --> com.fincom.functions.Function.goodbye
```

**Comment by FinVamp1** [comment] 2018-05-22 11:06
@JunyiYi can we have updated docs on this pattern as well? It would help customers on this area.

**Comment by brettsam** [comment] 2018-05-30 18:53
@pragnagopa -- should we close this issue, or do we need to keep it around?

**Comment by pragnagopa** [comment] 2018-06-12 21:48
moving this to backlog. We should improve error handling to let the users know we cannot load functions due to multiple jar files. Updating the documentation is not enough.

**Comment by pragnagopa** [comment] 2018-10-24 20:48
Verified that this works as expected on the latest bits
#212 enforces method name specified as entrypoint i.e using '@FunctionName' annotation to be unique in given class.

This is an improvement as now function invocation is more deterministic.

**Closed by pragnagopa** 2018-10-24 20:48 UTC
Labels: javafunctions-v2-GA-shouldhave
