### ISSUE TITLE
Dedicated app not able to start due to resource exhaustion

### ISSUE THREAD

**Issue by pragathikadaganchi** [Azure/azure-functions-java-worker#174] opened 2018-09-10 17:51 UTC
#### Investigative information

Error:

Function (checkOutCart) Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out.
Session Id: f9972f5d3d44415ea0f0b898622eef4f

- Timestamp:2018-09-10T17:46:17.426Z
- Function App name:scanandgo-warmup
- Function name(s) (as appropriate):
- Invocation ID: f9972f5d3d44415ea0f0b898622eef4f
- Region: WEST US

#### Repro steps

 <azure.functions.maven.plugin.version>1.0.0-beta-5</azure.functions.maven.plugin.version>
        <azure.functions.java.library.version>1.0.0-beta-5</azure.functions.java.library.version>

#### Related information 

Provide any related information 

* Programming language used : java

**Comment by pragnagopa** [comment] 2018-09-10 22:15
@pragathikadaganchi -  I do not have enough data in the backend logs to figure out why starting language worker keeps failing for your app. To help investigate further,
Can you please confirm if you can run these functions locally via [azure functions cli](https://github.com/Azure/azure-functions-core-tools)?

**Comment by pragathikadaganchi** [comment] 2018-09-10 22:36
The build was succeeded in local with azure cli
Below are the logs


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.31


[WARNING] Local version of Azure Functions Core Tools (2.0.1-beta.34) does not match the latest (2.0.1-beta.38). Please update it for the best experience. See: https://aka.ms/azfunc-install
[INFO] Function extension installation done.
[INFO] Successfully built Azure Functions.
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ scanandgo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-bin) @ scanandgo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\pkada00\IdeaProject\scanandgo-backend\bin
[INFO]
[INFO] --- azure-functions-maven-plugin:1.0.0-beta-5:run (default-cli) @ scanandgo ---
[INFO] Azure Function App's staging directory found at: C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\scanandgodev1
[INFO] Azure Functions Core Tools found.
your worker runtime is not set. As of 2.0.1-beta.26 a worker runtime setting is required.
Please run `func settings add FUNCTIONS_WORKER_RUNTIME <option>` or add FUNCTIONS_WORKER_RUNTIME to your local.settings.json
Available options: dotnet, node, java

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Skipping 'AzureWebJobsStorage' from local settings as it's already defined in current environment variables.
Skipping 'AzureWebJobsDashboard' from local settings as it's already defined in current environment variables.
Hosting environment: Production
Content root path: C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\scanandgodev1
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[9/10/2018 10:32:57 PM] Reading host configuration file 'C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\scanandgodev1\host.json'
[9/10/2018 10:32:57 PM] Host configuration file read:
[9/10/2018 10:32:57 PM] {}
[9/10/2018 10:32:57 PM] Starting Host (HostId=liv1934167l-1863653532, InstanceId=1ed3ebc7-7991-4ff0-a08c-64627633f87f, Version=2.0.11946.0, ProcessId=13728, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[9/10/2018 10:32:59 PM] Starting C:\Program Files\Java\jdk1.8.0_171\bin\java language worker process with Arguments= -jar "C:\Users\pkada00\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\java\azure-functions-java-worker.jar" --host 127.0.0.1 --port 52749 --workerId d0d58e84-3aec-42f1-8284-45e0a3ca605b --requestId cbc86dc0-a594-4c1a-8a5e-f8c8d0b3e376 --grpcMaxMessageLength 134217728
[9/10/2018 10:32:59 PM] C:\Program Files\Java\jdk1.8.0_171\bin\java process with Id=9128 started
[9/10/2018 10:32:59 PM] Generating 13 job function(s)
[9/10/2018 10:32:59 PM] Microsoft Azure Functions Java Runtime [build 1.1.0-beta8]
[9/10/2018 10:32:59 PM] Found the following functions:

When I deploy it to azure the error message was found saying failed to start language worker process for java.

Thanks,
Pragathi

From: Pragathi Kadaganchi
Sent: Monday, September 10, 2018 3:21 PM
To: 'Azure/azure-functions-java-worker' <reply@reply.github.com>; Azure/azure-functions-java-worker <azure-functions-java-worker@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: EXTERNAL: Re: [Azure/azure-functions-java-worker] Error: Failed to start language worker process for: java. (#174)

Yes, I can run those functions in local successfully.

**Comment by pragnagopa** [comment] 2018-09-10 23:59
Please update to the latest CLI and I come function virwCart locally.

**Comment by pragathikadaganchi** [comment] 2018-09-11 05:53
Hi,

I updated the azure cli to version 2.0.45 and made a new deployment, still the function runtime is unable to start.

Error:
The function runtime is unable to start.
Session Id: 28737f46878f445380512c349d6f69e9
Timestamp: 2018-09-11T05:50:29.220Z

**Comment by pragathikadaganchi** [comment] 2018-09-11 05:55
Few minutes after the deployment the error was changed.


Error:
Function (checkOutCart) Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 [SEVERE] {Application.main}: Unexpected Exception causes system to exit,java.lang.IllegalStateException: failed to create a child event loop,Caused by: io.netty.channel.ChannelException: failed to open a new selector.
Session Id: d13c95b293aa4eb28c32530f142be143
Timestamp: 2018-09-11T05:54:13.378Z

**Comment by pragnagopa** [comment] 2018-09-11 16:46
@pragathikadaganchi  - please run the function locally and see if it succeeds. Here are instructions to debug using VSCode  https://code.visualstudio.com/docs/java/java-azurefunctions

**Comment by pragathikadaganchi** [comment] 2018-09-11 16:51
Yes, It was success in local. I’m using intellij IDE

**Comment by pragnagopa** [comment] 2018-09-11 17:26
From the backend logs, starting grpc server is failing
```
System.IO.IOException : Failed to bind port "127.0.0.1:0"
   at Grpc.Core.Server.CheckPortsBoundSuccessfully()
   at Grpc.Core.Server.Start()
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcServer.StartAsync() at C:\azure-webjobs-sdk-script\src\WebJobs.Script.Grpc\Server\GrpcServer.cs : 34
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeWorkersAsync() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 473
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 238
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartHostAsync(CancellationToken cancellationToken,Int32 attemptCount,Boolean skipHostJsonConfiguration) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 89
```

Investigating

**Comment by pragathikadaganchi** [comment] 2018-09-11 17:30
Error while trying to install "*npm i -g azure-functions-core-tools@core"*

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\pkada00>npm install -g azure-functions-core-tools@core
C:\Users\pkada00\AppData\Roaming\npm\azfun -> C:\Users\pkada00\AppData\Roaming\n
pm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\pkada00\AppData\Roaming\npm\func -> C:\Users\pkada00\AppData\Roaming\np
m\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\pkada00\AppData\Roaming\npm\azurefunctions -> C:\Users\pkada00\AppData\
Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@2.0.1-beta.38 postinstall C:\Users\pkada00\AppData\
Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.0.1-beta.38/Azure
.Functions.Cli.win-x64.2.0.1-beta.38.zip"
Error: connect ETIMEDOUT 72.21.81.200:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@2.0.1-beta.38 postinstall: `node lib/install
.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@2.0.1-beta.38 postinstall scri
pt.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pkada00\AppData\Roaming\npm-cache\_logs\2018-09-11T17_27_2
1_319Z-debug

**Comment by pragnagopa** [comment] 2018-09-11 22:34
Root cause: Another app scanandgodemo1 running on the same worker was consuming too many ports and blocking starting app scanandgo-warmup

@pragathikadaganchi - As this is a dedicated app, once scanandgo-warmup is up and running it should continue to work. Please update this issue, if scanandgo-warmup stops working.

**Comment by pragnagopa** [comment] 2018-09-12 16:21
Updated the title to reflect the root cause.
App running on Small dedicated webworker role, failing with sandbox error:

```
Sandbox scanandgo-warmup (process id 22400 (w3wp.exe)) rejected API 'SocketConnect' due to exceeded limit of MaximumServerWideConnections=1920
```

**Comment by pragathikadaganchi** [comment] 2018-09-12 17:05
I have created the new instance of dedicated function app called scanandgodev1. the same issue reproduce s after certain time the function app is timing out with 3000ms,  if i stop and start again it works.

**Comment by pragnagopa** [comment] 2018-09-12 17:14
Here is the exception. You should see this in [application insights](https://azure.microsoft.com/en-us/updates/azure-functions-now-integrated-with-application-insights/) as well
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.getItemByScanCode ---> Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: Failure
Exception: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=scanandgodb.documents.azure.com:10255, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
Stack: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=scanandgodb.documents.azure.com:10255, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.getDescription(BaseCluster.java:167)
	at com.mongodb.Mongo.getConnectedClusterDescription(Mongo.java:885)
	at com.mongodb.Mongo.createClientSession(Mongo.java:877)
	at com.mongodb.Mongo$3.getClientSession(Mongo.java:866)
	at com.mongodb.Mongo$3.execute(Mongo.java:823)
	at com.mongodb.FindIterableImpl.first(FindIterableImpl.java:193)
	at com.safeway.dao.ScanAndGoFunctionDAO.getItemCollection(ScanAndGoFunctionDAO.java:61)
	at com.safeway.functions.ScanAndGoFunction.getItemByScanCode(ScanAndGoFunction.java:51)

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\Rpc\WorkerLanguageInvoker.cs : 74
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 84
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionGenerator.cs : 225
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 63
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 561
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 508
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 444
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 249 
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 293
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 89
```
This seems like a application code issue. Restarting the app is a temporary fix. Even if you scale up, you would run into same issues after certain amount of time.
You should fix the code to close the sockets/connections as overtime your application is hitting the limits.

**Comment by pragnagopa** [comment] 2018-09-20 16:16
This issue is addressed in https://github.com/Azure/azure-functions-host/issues/3444
More deatails on Socket exceptions for your app can be found here: https://blogs.msdn.microsoft.com/appserviceteam/2018/05/07/app-service-diagnostics-comes-to-functions-ase-and-more/

**Closed by pragnagopa** 2018-09-20 16:16 UTC
