### ISSUE TITLE
Reduce noise: 'org.reflections.ReflectionsException: could not get type for name' error during compilation

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-functions-java-worker#43] opened 2018-01-03 06:56 UTC
In a certain code situation, I get the following exception at compile time:

> [INFO] Step 1 of 6: Searching for Azure Function entry points
[INFO] Reflections took 27 ms to scan 1 urls, producing 2 keys and 2 values 
[WARNING] could not get type for name net.jonathangiles.azure.functions.interfacebug.db.DataStore from any class loader
org.reflections.ReflectionsException: could not get type for name net.jonathangiles.azure.functions.interfacebug.db.DataStore
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at com.microsoft.azure.maven.function.handlers.AnnotationHandlerImpl.findFunctions(AnnotationHandlerImpl.java:42)
	at com.microsoft.azure.maven.function.PackageMojo.findAnnotatedMethods(PackageMojo.java:89)
	at com.microsoft.azure.maven.function.PackageMojo.doExecute(PackageMojo.java:61)
	at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:265)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: net.jonathangiles.azure.functions.interfacebug.db.DataStore
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
	... 28 more
[INFO] 1 Azure Function entry point(s) found.

I'm attaching the code that caused this for you to reproduce the issue locally.

[interface-bug.zip](https://github.com/Azure/azure-functions-java-worker/files/1599583/interface-bug.zip)

**Comment by nicenemo** [comment] 2018-01-03 19:54
What do you try? `mvn compile` or `mvn package`?
If it is the last you probably you should use the shade plugin to copy alle dependencies. (works for me). 
Your pom.xml does not contain the shade plugin. 
I guess that If you trigger the function code from an integration test it should work but packaging or running it local fails.

**Comment by JonathanGiles** [comment] 2018-01-03 20:30
@nicenemo I'm wondering if this comment was intended for https://github.com/Azure/azure-functions-java-worker/issues/35 ? In any case, I'll answer your questions as they related to this interface issue I'm seeing (and I'll update issue 35 to answer your questions too).

This is during `mvn package`. I am using the standard generated scaffolding provided by the Maven Azure plugin, with no dependencies, and only a few extra classes that I wrote to demonstrate the issue. I'm not running the tests, or even accessing the function - this is simply during the packaging of the code - so the issue is present regardless of whether the shade plugin is used or not.

**Comment by JunyiYi** [comment] 2018-01-06 04:35
@xscript , please take a look. The problem is during the compilation stage.

**Comment by xscript** [comment] 2018-01-08 14:05
@JonathanGiles I tried your attached project and it builds successfully. The warning message you pasted above is coming from the reflection library we use. We will try to suppress it as it doesn't block the generation of `function.json`.
You can follow up on the fix of https://github.com/Microsoft/azure-maven-plugins/issues/76 .

**Comment by JonathanGiles** [comment] 2018-01-08 17:36
Thanks!

**Comment by nicenemo** [comment] 2018-01-08 18:56
That will save some noise in the build !!

**Comment by JonathanGiles** [comment] 2018-01-16 22:32
If issue Microsoft/azure-maven-plugins#76 is merged, does that mean that this issue should now be closed as resolved?

**Comment by xscript** [comment] 2018-01-17 01:13
@JonathanGiles The fix has not been released yet. We are planning to release a new version this week. Please stay tuned.
You can close this issue after verifying the fix in the next version of our maven plugin.
Thanks!

**Comment by JunyiYi** [comment] 2018-03-21 20:20
Close the issue due to lack of response from external for more than two months.

**Closed by JunyiYi** 2018-03-21 20:20 UTC
Labels: improvement, triaged, waiting for external
