### ISSUE TITLE
Support static methods in Java

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-java-worker#240] opened 2018-11-14 13:46 UTC
Not sure if there is a reason for this or not but a question came up here on why for every execution we create a new instance of the class that has your function instead of re-using objects across executions.  Prevents people for putting instantiation code in the constructor of the class with the intent of re-using.  In C# we require it's a static method, but here where we create an object and invoke I wonder if we could allow users to do that.  Seems like it'd be a nice experience.

I believe [this may be the line](https://github.com/Azure/azure-functions-java-worker/blob/80ad72fb02bfe266b9ef1de6939998fc9bc3e152/src/main/java/com/microsoft/azure/functions/worker/broker/JavaMethodExecutor.java#L54) that would be nice if it said "createIfNotExists" type logic.

/cc @brunoborges

**Comment by brunoborges** [comment] 2018-11-16 12:14
Going deeper, we should be either explicit of the behavior is set by the worker, or allow the user to dictate the behavior.

1) Be explicit: enforce that the entry method must be static. This can be verified by the Maven plugin and then double-checked by the worker during runtime.

This would enforce the developer to clearly understand the behavior, and then it would be able to circumvent and implement specific needs (e.g. shared objects). 

2) Allow user to define behavior: if the developer sets a method as static, then of course no new object is created because that's a static method. But the problem is that it requires developer to define everything else as static (e.g. objects used within the function method). If the developer sets a method as non-static, we could provide an @Annotation that would indicate whether objects should be reused or not.

**Comment by kaibocai** [comment] 2023-02-27 23:02
We don't have any customer that complains about this by far. I will go ahead closing this issue. 
If you really want this feature, you can do it through the [Dependency Injection Hook](https://github.com/Azure/azure-functions-java-worker/wiki/Dependency-Injection-on-Azure-Functions-Java) we provided.
Here is an example how you can resuse your function instance in every function invocation. https://github.com/kaibocai/reuse-function-instance-sample

**Closed by kaibocai** 2023-02-27 23:02 UTC
Labels: New Feature, needs-discussion, reviewed
