### ISSUE TITLE
Log messages show up twice in the functions runtime

### ISSUE THREAD

**Issue by nicenemo** [Azure/azure-functions-java-worker#42] opened 2018-01-02 11:05 UTC
## Expected
As a user of the Azure Functions runtime for Java I expect log messages to show up only once.
I log a message with
```Java
   logger.log(Level.SEVERE,"This should not be produced twice: " + System.currentTimeMillis());
```
I expect this message to be logged once.

## Actual
The message is logged twice.
Once without a '.' and once with a '.' concatenated to the message

Sample output:
```LOG
1/2/2018 11:00:05 AM] Function started (Id=174ad102-d561-41ba-97cd-c35d8a3b67b9)
[1/2/2018 11:00:05 AM] Executing 'Functions.hello' (Reason='This function was programmatically called via the host APIs.', Id=174ad102-d561-41ba-97cd-c35d8a3b67b9)
[1/2/2018 11:00:05 AM] A ScriptHost error has occurred
[1/2/2018 11:00:05 AM] This should not be produced twice: 1514890805254.
[1/2/2018 11:00:05 AM] This should not be produced twice: 1514890805254
[1/2/2018 11:00:05 AM]
[1/2/2018 11:00:05 AM] Function "3a627573-bd53-48be-b23a-9921a53febbc" executed
[1/2/2018 11:00:05 AM] Function completed (Success, Id=174ad102-d561-41ba-97cd-c35d8a3b67b9, Duration=289ms)
[1/2/2018 11:00:05 AM] Executed 'Functions.hello' (Succeeded, Id=174ad102-d561-41ba-97cd-c35d8a3b67b9)
```
## Sample code
```Java
package eu.hanskruse;

import java.util.*;
import java.util.logging.Logger;
import java.util.logging.Level;
import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;

public class Function {
    @FunctionName("hello")
    public HttpResponseMessage<String> hello(
            @HttpTrigger(name = "req", 
                                    methods = {"get", "post"},
                                    authLevel = AuthorizationLevel.ANONYMOUS) 
HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
        final Logger logger = context.getLogger();
        logger.log(Level.SEVERE,"This should not be produced twice: " + System.currentTimeMillis());

        // Parse query parameter
        String name = request.getQueryParameters().get("name");
        return request.createResponse(200, "Hello, " + name);
        
    }
}
```
I created a [Sample project](https://github.com/nicenemo/azfunctions-doublelogging) to illustrate this issue. This is a simplified version of the standard generated HelloWorld Archetype.

After cloning you can build and run it with:
```
mvn clean package azure-functions:package azure-functions:run
```
The double log entries can be produced by going to the following url in a browser:
[http://localhost:7071/api/hello?name=hans](http://localhost:7071/api/hello?name=hans)

**Comment by pragnagopa** [comment] 2018-01-08 23:03
@ JunyiYi - can you confirm if Java worker is not sending the duplicate logs?

**Comment by kevinhillinger** [comment] 2018-04-24 17:06
@pragnagopa @JunyiYi I attempted to duplicate this issue without success. Here are the steps taken:

#### Environments Tested
Local - Core Tools (220.0.0-beta.0 w/ 2.0.11651.0)
Azure - Function Runtime Version: 2.0.11651.0, Consumption Plan, West US 

#### Steps
1. create from latest archetype
2. update function body with the following:

```java
final Logger logger = context.getLogger();
logger.log(Level.SEVERE,"This should not be produced twice: " + System.currentTimeMillis());
```

3. Execute locally. Result: log message appears once
4. Deploy to azure and execute HTTP call. Result: log message appears once.

#### Output

```
2018-04-24T17:04:23.220 [Information] Executing 'Functions.hello2' (Reason='This function was programmatically called via the host APIs.', Id=c510602e-e12e-46b1-a40c-7e7a310dd6af)
2018-04-24T17:04:23.269 [Error] This should not be produced twice: 1524589463256
2018-04-24T17:04:23.366 [Information] Function "hello2" (ID: 79e975f2-d2fe-4927-b6a0-d39a6a6357e7) invoked by Java Worker
2018-04-24T17:04:23.367 [Information] Executed 'Functions.hello2' (Succeeded, Id=c510602e-e12e-46b1-a40c-7e7a310dd6af)
```

**Comment by pragnagopa** [comment] 2018-04-24 17:14
@kevinhillinger - Thank you for confirming. @JunyiYi - Can we close this issue?

**Comment by JunyiYi** [comment] 2018-04-24 17:56
Sure. I will close it since it is not reproducible any more.

**Closed by JunyiYi** 2018-04-24 17:56 UTC
Labels: bug, lang-Java
