### ISSUE TITLE
RpcHttpRequestDataSource cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by csellberg** [Azure/azure-functions-java-worker#255] opened 2018-12-23 07:13 UTC
I am experiencing the same error as reported as the first stack trace here

https://github.com/Azure/azure-functions-java-worker/issues/239

The ticket is closed based on a cast error on byte array ... but ... the two stack traces indicates two different issues. 

The issue solved in the ticket above is a cast error on a primitive byte array, but the first stack trace is related to an instance of RpcHttpRequestDataSource being cast to a String, which happens here

https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/binding/DataOperations.java#L91

Here DataOperations tries to cast the incoming value to a String. 

But, it seems that when RpcHttpRequestDataSource is initialized here

https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/binding/RpcHttpRequestDataSource.java#L27

Then it sets its value, to "itself" (i.e. to "this")

So that when computeByType is called here

https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/binding/DataSource.java#L56

Then it passes the instance of RpcHttpRequestDataSource (which now, as its value attribute, holds the value of the DataSource itself) to the apply method on DataOperations which then tries to cast it to a String here

https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/binding/DataOperations.java#L91

This gives the following same stack trace as in #239 and also in my local dev environment, shown below

[12/23/2018 06:08:35] Stack: java.lang.ClassCastException: com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource cannot be cast to java.lang.String
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:91)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:50)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[12/23/2018 06:08:35] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[12/23/2018 06:08:35] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12/23/2018 06:08:35] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12/23/2018 06:08:35] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12/23/2018 06:08:35] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12/23/2018 06:08:35] 	at java.lang.Thread.run(Thread.java:748)

Again, this is the exact same error as reported as the first stack trace here

https://github.com/Azure/azure-functions-java-worker/issues/239

Looking into the code it seems that the expectation of the framework is that the value set here

https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/binding/RpcHttpRequestDataSource.java#L27

Is the http request body presented as a String on not the instance of RpcHttpRequestDataSource "itself".

**Comment by tharangahewa** [comment] 2019-01-04 12:37
I have the same issue. Even though it is said that the issue with HttpTigger is fixed in #239, it is not. I cloned the repo and ran my function app on  Azure Functions Java Worker  version [ 1.2.3]. Issue with HttpTrigger still persists.

**Comment by pragnagopa** [comment] 2019-01-07 20:30
@csellberg / @tharangahewa - if possible please attach a simple repro. I will investigate.

**Comment by tharangahewa** [comment] 2019-01-09 12:38
**Below is the sample repo-** 
https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-azure

Above is a sample application for Spring Cloud Functions maintained by Spring Cloud team. Please add the version attribute to the host.json before you start. I added - "version": "2.0" 

**Function of concern -** 
```
public class FooHandler extends AzureSpringBootRequestHandler<Foo, Bar> {
    @FunctionName("uppercase")
    public Bar execute(
            @HttpTrigger(name = "req", methods = { HttpMethod.GET,
                    HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS) Foo foo,
            ExecutionContext context) {
        return handleRequest(foo, context);
    }  
}
```
Below is the error I encounter -

```
Executed 'Functions.uppercase' (Failed, Id=4fd6ef4c-209c-45cb-bf65-ce38e90b6620)
 System.Private.CoreLib: Exception while executing function: Functions.uppercase. System.Private.CoreLib: Result: Failure
 Exception: ClassCastException: com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource cannot be cast to java.lang.String
 Stack: java.lang.ClassCastException: com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource cannot be cast to java.lang.String
   at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:91)
   at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
   at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20)
   at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
   at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20)
   at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:50)
   at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
   at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
   at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52)
   at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
   at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
   at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
 .
```
Your help is appreciated

**Comment by pragnagopa** [comment] 2019-01-14 17:03
@tharangahewa - Function signature does not look right. A HttpTrigger function should like this:

```java
public static String HttpTriggerJavaMetadata(
        @HttpTrigger(name = "req", methods = {HttpMethod.GET, HttpMethod.POST}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<String>> request,
        @BindingName("firstName") String queryValue1, @BindingName("lastName") String queryValue2
    )
```

Note: Using @HttpTrigger annotation requires the input to be of type HttpRequestMessage which is defined in [azure-functions-java-library](https://github.com/Azure/azure-functions-java-library/). To specify a HttpRequest with input body as Bytes, use HttpRequestMessage<Optional<byte[]>>

**Comment by fabiocav** [comment] 2019-02-06 21:44
Closing due to inactivity. Please let us know if you continue to have issues.

**Closed by fabiocav** 2019-02-06 21:44 UTC

**Comment by damoodamoo** [comment] 2019-04-03 14:12
Just in case anyone else gets here - I ended up with this: 
` @HttpTrigger(name = "request", methods = {HttpMethod.POST}, authLevel = AuthorizationLevel.FUNCTION) HttpRequestMessage<Optional<MyPOJO>> request,`
...
`Optional<MYPOJO> r = request.getBody();
 message.setValue(r.get());
`

**Comment by DariusTClark** [comment] 2019-04-11 17:53
And if anyone else gets here after attempting to add a proxy to a previously working function with a parameterized route, I was able to resolve the issue by ensuring that the parameter names used in the proxy matched the names used for the function's route.

For example, with the below:
`@HttpTrigger(name = "req", methods = {HttpMethod.GET}, authLevel = AuthorizationLevel.ANONYMOUS, route = "getBrand/{brandName=NULL}") HttpRequestMessage req,
            @BindingName("brandName") String brandName,`

the following does not work:
`    "matchCondition": {
        "methods": ["GET"],
        "route": "/api/getBrand/{brand}/{building}/{lotNumber}"
      },
      "backendUri": "https://localhost/api/getBrand/{brand}"`

but this does:
`    "matchCondition": {
        "methods": ["GET"],
        "route": "/api/getBrand/{brandName}/{building}/{lotNumber}"
      },
      "backendUri": "https://localhost/api/getBrand/{brandName}"`

**Comment by nadworny** [comment] 2019-05-02 14:20
> ```java
> HttpRequestMessage<Optional<
> ```

I've tried that but still didn't work. Do you have a working example with a repo? That would be great.

**Comment by Shrirang97** [comment] 2021-10-25 17:26
@fabiocav 

https://github.com/Shrirang97/java-design-patterns/blob/claim-check-pattern-azure/claim-check-pattern/Call%20Usage%20App/src/main/java/com/iluwatar/producer/calldetails/functions/UsageDetailPublisherFunction.java

Please reopen above issue.

I created new issue https://github.com/Azure/azure-functions-java-worker/issues/477

**Comment by Shrirang97** [comment] 2021-10-25 17:34
> Just in case anyone else gets here - I ended up with this:
> 
> ```java
> @HttpTrigger(name = "request", methods = {HttpMethod.POST}, authLevel = AuthorizationLevel.FUNCTION) HttpRequestMessage<Optional<MyPOJO>> request,
> ```
> 
> ...
> 
> ```java
> Optional<MyPOJO> r = request.getBody();
> MyPOJO theObj = r.get();
> ```

not working again.

**Comment by djangofan** [comment] 2022-05-16 21:33
I am able to reproduce this bug.  Use the following DEMO repository: https://github.com/djangofan/mockito-experiment/blob/main/src/main/java/com/test/meta/HttpTriggerFunctions.java

The function at line # 27 and 41 both work.

The function at line # 55 (the createAlt function) does NOT work and throws the above reported error (or very similar).

Can someone try my repo and acknowledge or provide a solution?    I notice there is a behavior difference if I change my POJO LocalDate field to be a String instead, then it works.   I suspect it blows up on the LocalDate parsing during auto-deserialization???   Because of this, I suspect this is a bug in the Java library, concerning dates in POJOs?  **You can prove it simply by commenting out the `testDate` field in the POJO.**

I bet the Java SDK does not have a unit test for the JSR310 java date features, so I am the first to notice this?

NOTE1: You'll need Java11 and maven.
NOTE2: Using the older java.util.Date fields will work and deserializes with no error.

**Comment by AjayAsok** [comment] 2022-06-27 09:54
Hi,
I am facing the same issue.
Exception: ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@1222ab9ato type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<com.example.ToDoItem>>
Stack: java.lang.ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@1222ab9ato type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<com.example.ToDoItem>>
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataOperations.generalAssignment(DataOperations.java:191)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:120)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:62)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:53)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-06-27T09:50:50.646Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
[2022-06-27T09:50:50.646Z] .

I tried using the Sample mentioned in [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=in-process%2Cfunctionsv2&pivots=programming-language-java](url) .

`@FunctionName("TriggerPojoPost")
	public HttpResponseMessage run1(@HttpTrigger(name = "req", methods = {
			HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<ToDoItem>> request,
			final ExecutionContext context) {
		context.getLogger().info("Request body is: " + request.getBody());
		Optional<ToDoItem> r = request.getBody();
		ToDoItem theObj = (ToDoItem) r.get();
		context.getLogger().info("Request body is: " + theObj);
		// Item list
		context.getLogger().info("Request body is: " + request.getBody().orElse(null));

		// Check request body
		if (!request.getBody().isPresent()) {
			return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("Document not found.").build();
		} else {
			// return JSON from to the client
			// Generate document
			final ToDoItem body = (ToDoItem) request.getBody().get();
			return request.createResponseBuilder(HttpStatus.OK).header("Content-Type", "application/json").body(body)
					.build();
		}
	}`

Could anyone please help me on this?

**Comment by thomasmillercf** [comment] 2024-09-03 17:24
> Just in case anyone else gets here - I ended up with this:
> 
> ```java
> @HttpTrigger(name = "request", methods = {HttpMethod.POST}, authLevel = AuthorizationLevel.FUNCTION) HttpRequestMessage<Optional<MyPOJO>> request,
> ```
> 
> ...
> 
> ```java
> Optional<MyPOJO> r = request.getBody();
> MyPOJO theObj = r.get();
> ```

i love you
