### ISSUE TITLE
Can not create two functions under same function app.

### ISSUE THREAD

**Issue by SilicusShraddha** [Azure/azure-functions-java-worker#165] opened 2018-08-31 11:04 UTC
Hi,

With the release of new version -- [**Azure Functions V2 (2.0.12050-alpha)**](https://github.com/Azure/app-service-announcements/issues/132)
there seems to be breaking changes and the java code remain backward incompatible.

#### Investigative information
- Timestamp: 2018-08-31T10:52:43.221Z
- Invocation ID: 574e43788fea474a892fad937d79468d

**Problem 1 ::** With earlier azure functions, 2.x, I was able to create two functions under a single function app.
Ex. Function App (Ex. Calculator)
              --> Function 1 (Add)
              --> Function 2 (Subtract)
But now with the latest version, unable to deploy more than one function under same function app.

**Problem 2 ::** Continuously getting -- 500 error code in postman, where as logs shows--

Logs -- Starting language worker process:D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java  -jar "D:\Program Files (x86)\SiteExtensions\Functions\2.0.12050-alpha\32bit\workers\java\azure-functions-java-worker.jar" --host 127.0.0.1 --port 50864 --workerId b37ac37e-4a41-413d-8353-6f4a1fc1f89b --requestId f466bbbe-567e-4950-9f2b-0db88cea54e7 --grpcMaxMessageLength 33554432
Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . 

Please help.

**Comment by gcsuk** [comment] 2018-08-31 14:42
I just got off the phone with Microsoft, my c# functions went down this morning when they released the update.

The issue was known, and the fix he got me to do was to change `FUNCTIONS_EXTENSION_VERSION` from `beta` to `2.0.11961-alpha` and now it all works

He is emailing me a doc with the breaking changes and instructions for how to overcome them

**Comment by mhoeger** [comment] 2018-08-31 21:50
@SilicusShraddha - this shouldn't be the case. There was a change to not allow different languages in one function app, but assuming Function 1 (Add) and Function 2 (Subtract) are both Java functions, that shouldn't be the cause of the error. 

Here is a complete list of the breaking changes that came with the newest release: https://github.com/Azure/app-service-announcements/issues/129

Could you provide some more details of error messages you're seeing?

**Comment by gcsuk** [comment] 2018-09-01 14:38
I followed the docs and it’s all working back on beta, it involves updating the sdk to v19 in nugget and also storage emulator to latest, then publish. Sorted everything out.

**Comment by SilicusShraddha** [comment] 2018-09-04 12:55
@mhoeger , yes, my both the functions are written in same language (java). But, even for a single function, its giving me error, and is unstable with **version 2.0.12050-alpha**

Below is the error.

**[Error] Language Worker Process exited.
Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 .**

**Comment by SilicusShraddha** [comment] 2018-09-04 13:03
@gcsuk , I am trying to deploy JAVA azure functions, could you please help me with the step wise doc, what all needs to be done in order to run it successfully?

Coz, i am facing issues with both of the versions of FUNCTIONS_EXTENSION_VERSION  to "2.0.11961-alpha" and "beta". Getting error 
**[Error] Language Worker Process exited.
Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 .**

**Comment by mhoeger** [comment] 2018-09-04 18:34
@pragnagopa - do you know of any changes that could have caused this?

**Comment by pragnagopa** [comment] 2018-09-04 18:37
No changes in how we load the java functions. I will look into the logs and update this issue.

**Comment by pragnagopa** [comment] 2018-09-12 22:42
We have identified root cause to be https://github.com/Azure/azure-functions-host/issues/3081 and we are in the process of deploying fix to production. Closing this issue for now. Please reactive if you still run into issue after deployment of function runtime mentioned here https://github.com/Azure/app-service-announcements/issues/134

**Closed by pragnagopa** 2018-09-12 22:42 UTC

**Comment by SilicusShraddha** [comment] 2018-09-14 05:29
Is the function version **2.0.12093-alpha released to production?** Is it globally available now? Coz, as announced, we must be using 2.0.12093-alpha instead of **2.0.12080**, right?
I am getting below warning when i deployed my function pinned to version 2.0.12093-alpha.
And with 2.0.12050, still getting **500 error, [Error] Executed 'Functions.HttpTrigger-Java' (Failed, Id=b78eda84-8c64-4b26-a8ee-e91c2582808b)**

![image](https://user-images.githubusercontent.com/36947393/45531361-11f2a380-b80d-11e8-9633-73dd0df8a779.png)
